import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import FirstHeader from '@/components/layouts/FirstHeader'
import SlideCircleProduct from '@/components/layouts/SlideCircleProduct'
import SlideSquareProduct from '@/components/layouts/SlideSquareProduct'
import { recommandData } from '@/types/type'
import { useState, useEffect } from 'react'
import axios from 'axios'


export default function Cake() {
  return (
    <>
      <Head>
        <title>Main App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favic
        rfon.ico" />
      </Head>
      
    </>
  )
}
