import "@/styles/globals.css";
import "../public/assets/css/style.css";
import type { AppProps } from "next/app";
import { RecoilRoot } from "recoil";
import SubpageModal from "@/components/sections/SubpageModal";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
    <Head>
    <title>Sphabucks Online Store </title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="icon"
      href="/favic
    rfon.ico"
    />
  </Head>
    <RecoilRoot>
      <SubpageModal />
      <Component {...pageProps} />
    </RecoilRoot>
    </>
  );
}
