import Head from "next/head";
import { useRouter } from "next/router";

import { useState, useEffect } from "react";

import FirstHeader from "@/components/sections/FirstHeader";
import ProductBestList from "@/components/layouts/ProductBestList";
import TopScrollBtn from "@/components/ui/TopScrollBtn";
import axios from "axios";

import { productBestList } from "@/types/type";

export default function Best() {
  const [data, setData] = useState<productBestList[]>([]);
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    const BaseUrl = process.env.baseApiUrl;
    axios
      .get(`${BaseUrl}/api/v1/product/get-best/${router.query.category}`)
      .then((res) => {
        setData(res.data.data);
        setIsLoading(false);
      })
      .catch((err) => console.log(err));
  }, [router.query.category]);

  return (
    <>
      <Head>
        <title>starbucks best page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/favic
        rfon.ico"
        />
      </Head>

      {isLoading && (
        <div className="ui segment">
          <div className="ui active loader"></div>
          <p></p>
        </div>
      )}
      {!isLoading && (
        <>
          <TopScrollBtn />
          <FirstHeader />
          <ProductBestList itemData={data} />
        </>
      )}
    </>
  );
}
