import Head from 'next/head'
import FirstHeader from '@/components/layouts/FirstHeader'
import ProductBestList from '@/components/layouts/ProductBestList'
import axios from 'axios'
import { useState, useEffect } from 'react'
import { productBestList } from '@/types/type'
import { useRouter } from 'next/router'


export default function Best() {
  const [data, setData] = useState<productBestList[]>([])

  const BaseUrl = process.env.baseApiUrl;
const count = data.length;
console.log('count',count)
  const router = useRouter();
  console.log('router',router) //router {pathname: '/best', route: '/best', query: {…}, asPath: '/best?category=1', components: {…}, …}
  console.log('router.query.category',router.query.category) //router.query.category 1
  useEffect(() => {
    axios.get(`${BaseUrl}/api/v1/product/get-best/${router.query.category}`)
    .then( res => {
      console.log('res',res.data)
      setData(res.data)
    })
    .catch( err  => console.log( err ))
  },[router.query.category])
  return (
    <>
      <Head>
        <title>Best-Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favic
        rfon.ico" />
      </Head>
      <FirstHeader />
      <ProductBestList
        itemData={data} 
      />
      
    </>
  )
}
