import FilterHeader from "@/components/pages/filter/FilterHeader";
import axios from "axios";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { eventProductList } from "@/types/type";
import ProfuctFilterList from "@/components/pages/filter/ProductFilterList";
import { filterProductList } from "@/types/type";
import Header from "@/components/sections/Header";
import Head from "next/head";
import FirstHeader from "@/components/sections/FirstHeader";
export default function filter(props: {
  id: number;
  imgUrl: string;
  itemData: eventProductList[];
}) {
  const { query, asPath } = useRouter();
  const [productList, setProductList] = useState<filterProductList[]>([]);
  const BaseUrl = process.env.baseApiUrl;

  useEffect(() => {
    axios
      .get(`${BaseUrl}/api/v1/product/search2?${asPath.split("?")[1]}`)
      .then((res) => {
        setProductList(res.data.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [asPath]);
  return (
    <>
      <Head>
        <title>starbucks product filter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicrfon.ico" />
      </Head>
      <FirstHeader/>
      <FilterHeader />
      <ProfuctFilterList itemData={productList} />
    </>
  );
}
