import axios from "axios";
import React, { useEffect, useState } from "react";

import { useRouter } from "next/router";
import Head from "next/head";

import { filterProductList } from "@/types/type";

import ProfuctFilterList from "@/components/pages/filter/ProductFilterList";
import FirstHeader from "@/components/sections/FirstHeader";
import FilterHeader from "@/components/pages/filter/FilterHeader";

export default function Filter() {
  const {asPath } = useRouter();
  const [productList, setProductList] = useState<filterProductList[]>([]);

  useEffect(() => {
    const BaseUrl = process.env.baseApiUrl;
    axios
      .get(`${BaseUrl}/api/v1/product/search2?${asPath.split("?")[1]}`)
      .then((res) => {
        setProductList(res.data.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [asPath]);

  return (
    <>
      <Head>
        <title>starbucks product filter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicrfon.ico" />
      </Head>
      <FirstHeader/>
      <FilterHeader />
      <ProfuctFilterList itemData={productList} />
    </>
  );
}
