import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import FirstHeader from '@/components/sections/FirstHeader'
import SlideCircleProduct from '@/components/layouts/SlideCircleProduct'
import SlideSquareProduct from '@/components/layouts/SlideSquareProduct'
import { recommandData } from '@/types/type'
import { useState, useEffect } from 'react'
import axios from 'axios'
import SliderContainer from '@/components/layouts/Slide'

export default function Home() {
  const [data, setData] = useState<recommandData[]>([])
  const BaseUrl = process.env.baseApiUrl;
  useEffect(() => {
    axios.get(`${BaseUrl}/api/v1/event-products/get/recommendMD`)
    .then( res => {
      setData(res.data)
    })
    .catch( err  => console.log( err ))
  },[])
  return (
    <>
      <Head>
        <title>Main App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favic
        rfon.ico" />
      </Head>
      <FirstHeader />
      <SliderContainer/>
      <SlideCircleProduct />
      {
        data && data.map( item => (
          <SlideSquareProduct 
            key={item.id}
            title={item.name}
            itemData={item.data}
            description={item.description}
          />
        ))
      }
    </>
  )
}
