import SecondHeader from "@/components/layouts/SecondHeader";
import FooterBtn from "@/components/ui/FooterBtn";
import LoginMain from "@/components/sections/LoginMain";
import LoginHeader from "@/components/sections/LoginHeader";
import Head from "next/head";
export default function Login() {
  return (
    <>
      <Head>
        <title>starbucks login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/favic
        rfon.ico"
        />
      </Head>
      <LoginHeader />
      <LoginMain />
      <FooterBtn title={"로그인"}></FooterBtn>
    </>
  );
}
