import Head from "next/head";
import { useRecoilState } from "recoil";
import { userState } from "@/state/userState";

import FirstHeader from "@/components/sections/FirstHeader";
import MyPageTop from "@/components/sections/MyPageTop";
import MypageMenuLists from "@/components/sections/MyPageMenuLists";
import Logincheck from "@/components/ui/Logincheck";
import SecondHeader from "@/components/layouts/SecondHeader";

export default function Mypage() {
  const [loginData, setLoginData] = useRecoilState(userState);
  return (
    <>
      <Head>
        <title>starbucks mypage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/favic
            rfon.ico"
        />
      </Head>
      {loginData.isLogin === true ? (
        <>
          <FirstHeader />
          <MyPageTop />
          <MypageMenuLists title={"서비스"} />
          <MypageMenuLists title={"약관 및 정책"} />
        </>
      ) : (
        <>
          <SecondHeader title={"온라인스토어"}/>
          <Logincheck/>
        </>
      )}
    </>
  );
}
