import FirstHeader from "@/components/sections/FirstHeader";
import Head from "next/head";
import MyPageTop from "@/components/sections/MypageTop";
import MypageMenuLists from "@/components/sections/MyPageMenuLists";
export default function Mypage() {
    return(
        <>
        <Head>
          <title>mypage</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="icon"
            href="/favic
            rfon.ico"
          />
        </Head>
        <FirstHeader />
        <MyPageTop/>
        <MypageMenuLists/>
        <MypageMenuLists/>
</>
    )
}
